### PR TITLE
Lazy text

### PR DESCRIPTION
**Pull request by dten**
Hey I've been profiling some large sets of data that produced a quite sizeable .hp file (10GB)

it's impossible to get that through hp2pretty

I'm proposing rather than read the entire file in at startup as strict Text, stream the text through the function as lazy Text. Sadly in the current state this means reading the file twice as hp2pretty is not a single pass over the input. Also changing the `Header` type to have strict fields.

These two changes together mean that rather than using 100GB and falling over, hp2pretty completes only using < 20MB

n.b. this branch also includes the latest changes from upstream

### CODE REVIEW

**Comment by dten** [comment]
before and afters (i killed the before long before it completed but you get the idea, but the time value is not representative)

image

image

**Comment by pepeiborra** [comment]
That's pretty awesome!
Bear with me, I have a vague memory of contributing a minor bug fix to hp2pretty, did I also agree to review PRs?

**Comment by dten** [comment]
another before and after, this time a complete run on a 400MB hp file
24s vs 30s
800MB vs 2MB

image
image

**Comment by dten** [comment]
haha sorry @pepeiborra ! this was the closest to something that looked like a repo i could do a PR to :D if you know where it should be I can redirect these commits

**Comment by dten** [comment]
if I apply my brain it looks like I should direct these at @claudeha

**Comment by pepeiborra** [comment]
That's right. And please make sure this makes it into Hackage, awesome work

**Comment by claudeha** [comment]
Thanks for getting my attention. I should be able to apply those two commits (any others I should check?) to my repository at code.mathr.co.uk/hp2pretty and make a new release soon (I accept patches via email also).

Have you tried using a strict pair type?  `::!(Double, Double)` is only strict in the tuple constructor, not the tuple contents.

**Comment by dten** [comment]
Great I'll close this PR 👍  (sorry @pepeiborra for the confusion!)

I didn't try a strict pair as this seemed enough to give a flat graph and the tuple swap is slightly more effort than the Text one

**Comment by dten** [comment]
oh i just realised i missed making the streaming change in the multiple files case

**Comment by dten** [comment]
i added a commit for that too now
https://github.com/dten/hp2pretty/commits/lazy-text

**Pull request closed without merging**
